repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: git://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
  - id: forbid-tabs
    exclude_types: [python, javascript, dtd, markdown, makefile]
    exclude: binary|\.bin$
- repo: git://github.com/kintoandar/pre-commit.git
  rev: v2.1.0
  hooks:
  - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.1.0
  stages:
  - commit
  - push
  hooks:
  -   id: detect-aws-credentials
  -   id: detect-private-key
- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.4
  hooks:
  - id: shell-lint
- repo: https://github.com/ansible/ansible-lint
  rev: v4.0.1
  hooks:
  - id: ansible-lint
- repo: git://github.com/igorshubovych/markdownlint-cli
  rev: v0.13.0
  hooks:
  - id: markdownlint
- repo: local
  hooks:
  - id: talisman-precommit
    name: talisman
    entry: bash -c 'if [ -n "${TALISMAN_HOME:-}" ]; then ${TALISMAN_HOME}/talisman_hook_script pre-commit; else echo "TALISMAN does not exist. Consider installing from https://github.com/thoughtworks/talisman . If you already have talisman installed, please ensure TALISMAN_HOME variable is set to where talisman_hook_script resides, for example, TALISMAN_HOME=${HOME}/.talisman/bin"; fi'
    language: system
    pass_filenames: false
    types: [text]
    verbose: true
