---
# yamllint disable rule:line-length
name: Verify
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions: read-all

env:
  terraform: 1.3.0
  tf_target_dir: example/examplea
  branch: master
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  GITHUB_API_TOKEN: ${{ github.token }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2.0.3
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - name: Config Terraform plugin cache
        run: |
          echo "plugin_cache_dir=$HOME/.terraform.d/plugin-cache" >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache
      - name: Cache Terraform
        uses: actions/cache@v3.2.4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.tf_target_dir }}
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.tf_target_dir }}
      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.tf_target_dir }}
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
          fetch-depth: '0'
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9
      - run: |
          pip3 install lastversion
          lastversion terraform-docs --assets -d --verbose
          mkdir "$GITHUB_WORKSPACE/bin"
          tar -xvf terraform-docs*.tar.gz --directory "$GITHUB_WORKSPACE/bin"
          chmod +x "$GITHUB_WORKSPACE/bin/terraform-docs"
          wget https://github.com/rhysd/actionlint/releases/download/v1.6.23/actionlint_1.6.23_linux_amd64.tar.gz
          tar -xvf actionlint_1.6.23_linux_amd64.tar.gz --directory "$GITHUB_WORKSPACE/bin"
          chmod +x "$GITHUB_WORKSPACE/bin/actionlint"
          echo "$GITHUB_WORKSPACE/bin" >> "$GITHUB_PATH"
      - uses: pre-commit/action@v3.0.0
  version:
    permissions: write-all
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
    needs: [terraform, security]
